// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcGW-MUAhRnuT5BN3lSKBm-36z5f6OrLY',
    appId: '1:362392925241:android:9a4ec2645816c1765509e8',
    messagingSenderId: '362392925241',
    projectId: 'e-shop-2ece5',
    storageBucket: 'e-shop-2ece5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYxJYAEKIpQi1OlAog3YkfYC0tnFbDQG4',
    appId: '1:362392925241:ios:9d0796b62854ddb15509e8',
    messagingSenderId: '362392925241',
    projectId: 'e-shop-2ece5',
    storageBucket: 'e-shop-2ece5.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYxJYAEKIpQi1OlAog3YkfYC0tnFbDQG4',
    appId: '1:362392925241:ios:9d0796b62854ddb15509e8',
    messagingSenderId: '362392925241',
    projectId: 'e-shop-2ece5',
    storageBucket: 'e-shop-2ece5.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );
}
